server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://192.168.77.138:3306/test?serverTimezone=GMT%2B8&useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456

